# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: cimg/php:7.3.31-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mysql:9.4

    working_directory: ~/repo

    steps:
      - checkout
      - run: sudo apt update
      - run: sudo apt install -y php7.3-sqlite3
      - run: sudo composer self-update --2
      # Download and cache dependencies
      - restore_cache:
          keys:
          - composer-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - composer

      - run: composer install -n --prefer-dist --ignore-platform-reqs

      - save_cache:
          paths:
            - ./vendor
          key: composer-{{ checksum "composer.json" }}


      # run tests!
      - run: ./vendor/bin/phpunit
